version: '3.9'

services:
  db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_DB: ${SQL_DATABASE}
      POSTGRES_USER: ${SQL_USER}
      POSTGRES_PASSWORD: ${SQL_PASSWORD}
    ports:
      - ${SQL_PORT_PUBLISHED}:${SQL_PORT_TARGET}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  django:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
    ports:
      - ${DJANGO_PORT_PUBLISHED}:${DJANGO_PORT_TARGET}
    volumes:
      - .:/app
    env_file:
      - .env

volumes:
  postgres_data:
